# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - MathService/*
    exclude:
    - WebAPI/*
    - AzureTemplate/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  wcfService: '**/MathService/MathService.csproj"'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build WCF Service'
  inputs:
    solution: '$(wcfService)'
    msbuildArgs: '/p:OutputPath="$(build.artifactStagingDirectory)\WCFService.zip" /p:OutDir="$(build.artifactStagingDirectory)" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WCFService.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish $(wcfService) artifact'
  inputs:
    pathtoPublish: 'd:\a\1\a\_PublishedWebsites\MathService_Package\MathService.zip'
    artifactName: 'wcfService' 
